/*
 *
 * ExperimentList constants
 *
 */

export const GET_DATA = 'app/ExperimentList/GET_DATA';
export const LOAD_EXPERIMENT_DATA = 'app/ExperimentList/LOAD_EXPERIMENT_DATA';
export const LOAD_EXPERIMENT_DATA_SUCCESS =
  'app/ExperimentList/LOAD_EXPERIMENT_DATA_SUCCESS';
export const LOAD_EXPERIMENT_DATA_ERROR =
  'app/ExperimentList/LOAD_EXPERIMENT_DATA_ERROR';
export const SET_EXPERIMENT_COLUMNS =
  'app/ExperimentList/SET_EXPERIMENT_COLUMNS';


export const CREATE_EXPERIMENT_LABELS =
  'app/ExperimentList/CREATE_EXPERIMENT_LABELS';
export const CREATE_EXPERIMENT_LABELS_SUCCESS =
  'app/ExperimentList/CREATE_EXPERIMENT_LABELS_SUCCESS';
export const CREATE_EXPERIMENT_LABELS_ERROR =
  'app/ExperimentList/CREATE_EXPERIMENT_LABELS_ERROR';

export const DELETE_EXPERIMENT_LABELS =
  'app/ExperimentList/DELETE_EXPERIMENT_LABELS';
export const DELETE_EXPERIMENT_LABELS_SUCCESS =
  'app/ExperimentList/DELETE_EXPERIMENT_LABELS_SUCCESS';
export const DELETE_EXPERIMENT_LABELS_ERROR =
  'app/ExperimentList/DELETE_EXPERIMENT_LABELS_ERROR';

export const ADD_DELETE_EXPERIMENT_ID = 'app/ExperimentList/ADD_DELETE_EXPERIMENT_ID';
export const REMOVE_DELETE_EXPERIMENT_ID = 'app/ExperimentList/REMOVE_DELETE_EXPERIMENT_ID';
export const CLEAR_DELETE_EXPERIMENTS = 'app/ExperimentList/CLEAR_DELETE_EXPERIMENTS';

export const SUBMIT_DELETE_EXPERIMENTS = 'app/ExperimentList/SUBMIT_DELETE_EXPERIMENTS';
export const SUBMIT_DELETE_EXPERIMENTS_SUCCESS = 'app/ExperimentList/SUBMIT_DELETE_EXPERIMENTS_SUCCESS';
export const SUBMIT_DELETE_EXPERIMENTS_ERROR = 'app/ExperimentList/SUBMIT_DELETE_EXPERIMENTS_ERROR';
