version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
  web:
    build: .
    container_name: web
    restart: always
    command: ["bash", "wait-for-postgres.sh", "db", "bash", "runserver_dev.sh"]
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - MODELCHIMP_PATH=/code
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build: .
    command: bash wait-for-postgres.sh db celery -A settings worker -l info -B
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web
  ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    command: npm run start
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/frontend
      - /frontend/node_modules
    depends_on:
      - db
      - redis
      - web
    ports:
      - 3000:3000
