version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - /var/run/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    links:
      - web
      - ui
      - socket
    logging:
      driver: awslogs
      options:
        awslogs-group: modelchimp-cluster
        awslogs-region: us-west-1
        awslogs-stream-prefix: nginx
  redis:
    image: redis
    ports:
      - 6379:6379
    logging:
      driver: awslogs
      options:
        awslogs-group: modelchimp-cluster
        awslogs-region: us-west-1
        awslogs-stream-prefix: redis
  web:
    image: modelchimp/modelchimp-server:latest
    restart: always
    command: ["gunicorn", "--access-logfile", "-", "--workers", "3","-b", "0.0.0.0:8002",  "settings.wsgi:application"]
    ports:
      - "8000:8000"
    links:
      - redis
    logging:
      driver: awslogs
      options:
        awslogs-group: modelchimp-cluster
        awslogs-region: us-west-1
        awslogs-stream-prefix: web
    volumes:
      - /var/run/.env:/code/.env
  socket:
    image: modelchimp/modelchimp-server:latest
    restart: always
    command: ["daphne", "-b", "0.0.0.0", "-p", "8001", "settings.asgi:application"]
    ports:
      - "8001:8001"
    links:
      - redis
    logging:
      driver: awslogs
      options:
        awslogs-group: modelchimp-cluster
        awslogs-region: us-west-1
        awslogs-stream-prefix: web-socket
    volumes:
      - /var/run/.env:/code/.env
  celery:
    image: modelchimp/modelchimp-server:latest
    command: celery -A settings worker -l info -B
    links:
      - redis
    logging:
      driver: awslogs
      options:
        awslogs-group: modelchimp-cluster
        awslogs-region: us-west-1
        awslogs-stream-prefix: celery
    volumes:
      - /var/run/.env:/code/.env
  ui:
    image: modelchimp/modelchimp-ui:latest
    command: npm run start:prod
    ports:
      - 3000:3000
    logging:
      driver: awslogs
      options:
        awslogs-group: modelchimp-cluster
        awslogs-region: us-west-1
        awslogs-stream-prefix: ui
