version: '3'

services:
  db:
    image: postgres:10.6
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
  web:
    build:
      context: .
      dockerfile: Dockerfile-hub
    container_name: web
    restart: always
    command: ["bash", "./scripts/wait-for-postgres.sh", "db", "bash", "runserver.sh"]
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - MODELCHIMP_PATH=/code
      - DOMAIN=127.0.0.1:3000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  celery:
    build:
      context: .
      dockerfile: Dockerfile-hub
    command: bash ./scripts/wait-for-postgres.sh db celery -A settings worker -l info -B
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - web
