# base image
FROM node:11.5.0 as client-builder

# set working directory
#RUN mkdir /frontend
WORKDIR /frontend

# add `/frontend/.bin` to $PATH
ENV PATH /frontend/.bin:$PATH

COPY client/package.json client/package-lock.json /frontend/
RUN apt-get update && apt-get install libglu1 -y
RUN npm install

# install and cache app dependencies
COPY client/ /frontend/

RUN npm run build


FROM python:3.6.7-stretch
ENV PYTHONUNBUFFERED 1
ADD requirements.txt /code/
WORKDIR /code
RUN pip install --upgrade setuptools
RUN pip install -r requirements.txt

RUN apt-get update && apt-get install -y postgresql-client

COPY . /code
COPY --from=client-builder /frontend/build /code/client/build
RUN python manage.py collectstatic --noinput

EXPOSE 8000
