from django.conf.urls import include
from django.urls import path, re_path
from modelchimp.views.api import (project,
                                  experiment,
                                  comment,
                                  invitation,
                                  experiment_custom_object,
                                  experiment_mat_plot,
                                  project_key,
                                  experiment_image,
                                  experiment_label,
                                  experiment_param,
                                  experiment_metric,
                                  experiment_meta,
                                  experiment_code,
                                  experiment_gridsearch,
                                  experiment_asset,
                                  user)
from rest_framework.authtoken import views


urlpatterns = [
    path(r'project/', project.ProjectAPI.as_view(), name='project'),
    path(r'project/<int:project_id>/', project.ProjectAPI.as_view(), name='project'),
    path(r'project/<int:project_id>/param-metric/meta/', project.param_metric_meta),
    path(r'project/<int:project_id>/param-metric/data/', project.param_metric_data),
    path(r'project/key/<int:project_id>/', project_key.ProjectKeyAPI.as_view({'get': 'retrieve'}), name='project_dashboard_parameter_metric_filter'),
    path(r'project/key/decode/', project_key.decode_key, name='decode-key'),

    path(r'experiment/delete/<int:project_id>/', experiment.DeleteExperimentAPI.as_view(), name='delete_experiment'),
    path(r'experiment/list/<int:project_id>/', experiment.ListExperimentAPI.as_view(), name='list_experiment'),
    path(r'experiment/create/<int:project_id>/', experiment.CreateExperimentAPI.as_view(), name='create_experiment'),
    path(r'experiment/<int:model_id>/comment/', comment.CommentAPI.as_view(), name='comment_api'),
    path(r'experiment/<int:model_id>/custom-object/create/', experiment_custom_object.ExperimentCustomObjectAPI.as_view(), name='experiment_custom_object_create'),
    path(r'experiment/<int:model_id>/custom-object/retrieve/', experiment_custom_object.ExperimentCustomObjectAPI.as_view(), name='experiment_custom_object_retrieve'),
    path(r'experiment/<int:model_id>/custom-object/list/', experiment_custom_object.ExperimentCustomObjectDetailAPI.as_view(), name='experiment_custom_object_details'),
    path(r'experiment/<int:model_id>/matplot/', experiment_mat_plot.ExperimentMatPlotAPI.as_view(), name='experiment_mat_plot'),
    # path(r'experiment-pull-param/', experiment_pull_params.ExperimentPullParamAPI.as_view(), name='experiment_pull_params'),
    path(r'experiment/<int:project_id>/images/create/', experiment_image.ExperimentImageCreateAPI.as_view(), name='experiment_image_add_image'),
    path(r'experiment/<int:model_id>/images/list/', experiment_image.ExperimentImageListAPI.as_view(), name='experiment_image_data'),
    path(r'experiment/<int:model_id>/images/filter/', experiment_image.ExperimentImageFilterAPI.as_view(), name='experiment_image_filter'),
    path(r'experiment/<int:model_id>/label/', experiment_label.ExperimentLabelAPI.as_view(), name='experiment_label_create'),
    path(r'experiment/<int:model_id>/param/', experiment_param.ExperimentParamAPI.as_view({'get': 'retrieve'}), name='experiment_param'),
    path(r'experiment/<int:model_id>/metric/', experiment_metric.ExperimentMetricAPI.as_view({'get': 'retrieve'}), name='experiment_metric'),
    path(r'experiment/<int:model_id>/meta/', experiment_meta.ExperimentMetaAPI.as_view({'get': 'retrieve'}), name='experiment_meta'),
    path(r'experiment/<int:model_id>/code/', experiment_code.ExperimentCodeAPI.as_view({'get': 'retrieve'}), name='experiment_code'),
    path(r'experiment/<int:model_id>/object/', experiment_custom_object.ExperimentCustomObjectDetailAPI.as_view(), name='experiment_object'),
    path(r'experiment/<int:model_id>/gridsearch/', experiment_gridsearch.ExperimentGridSearchAPI.as_view({'get': 'retrieve'}), name='experiment_gridsearch'),
    path(r'experiment/<int:model_id>/asset/', experiment_asset.ExperimentAssetAPI.as_view(), name='experiment_asset'),
    path(r'experiment/<int:model_id>/asset/meta-fields/', experiment_asset.get_asset_meta_fields, name='experiment_asset_meta'),
    path(r'experiment/<int:model_id>/asset/<int:asset_id>/', experiment_asset.get_asset_blob, name='experiment_asset_blob'),

    path(r'invite/create/<int:project_id>/', invitation.InviteAPI.as_view(), name='invite_create'),
    re_path(r'invite/(?P<invite_id>[0-9A-Za-z_\-]+)/', invitation.InviteInfoAPI.as_view(), name='invite_info'),
    path(r'rest-auth/password/reset/confirm/', user.PasswordResetConfirmAPIView.as_view()),
    path(r'rest-auth/', include('rest_auth.urls')),
    path(r'api-token-auth/', views.obtain_auth_token),
    path(r'user', user.UserAPI.as_view({'get': 'retrieve', 'post': 'update'}), name='user'),
    path(r'register', user.RegisterAPI.as_view({'post': 'create'}), name='register'),
]
