export const LOAD_EXPERIMENT_DETAIL =
  'app/ExperimentDetail/LOAD_EXPERIMENT_DETAIL';
export const LOAD_EXPERIMENT_DETAIL_SUCCESS =
  'app/ExperimentDetail/LOAD_EXPERIMENT_SUCCESS';
export const LOAD_EXPERIMENT_DETAIL_ERROR =
  'app/ExperimentDetail/LOAD_EXPERIMENT_ERROR';

export const CREATE_EXPERIMENT_LABELS =
  'app/ExperimentDetail/CREATE_EXPERIMENT_LABELS';
export const CREATE_EXPERIMENT_LABELS_SUCCESS =
  'app/ExperimentDetail/CREATE_EXPERIMENT_LABELS_SUCCESS';
export const CREATE_EXPERIMENT_LABELS_ERROR =
  'app/ExperimentDetail/CREATE_EXPERIMENT_LABELS_ERROR';

export const DELETE_EXPERIMENT_LABELS =
  'app/ExperimentDetail/DELETE_EXPERIMENT_LABELS';
export const DELETE_EXPERIMENT_LABELS_SUCCESS =
  'app/ExperimentDetail/DELETE_EXPERIMENT_LABELS_SUCCESS';
export const DELETE_EXPERIMENT_LABELS_ERROR =
  'app/ExperimentDetail/DELETE_EXPERIMENT_LABELS_ERROR';


export const ON_EXPERIMENT_TAB_SELECT = 'app/ExperimentDetail/ON_EXPERIMENT_TAB_SELECT';

export const EXPERIMENT_TAB_METRICS = 'app/ExperimentDetail/EXPERIMENT_TAB_METRICS';
export const EXPERIMENT_TAB_PARAMETERS = 'app/ExperimentDetail/EXPERIMENT_TAB_PARAMETERS';
export const EXPERIMENT_TAB_CODE = 'app/ExperimentDetail/EXPERIMENT_TAB_CODE';
export const EXPERIMENT_TAB_CHARTS = 'app/ExperimentDetail/EXPERIMENT_TAB_CHARTS';
export const EXPERIMENT_TAB_OBJECTS = 'app/ExperimentDetail/EXPERIMENT_TAB_OBJECTS';
export const EXPERIMENT_TAB_GRIDSEARCH = 'app/ExperimentDetail/EXPERIMENT_TAB_GRIDSEARCH';
export const EXPERIMENT_TAB_ASSET = 'app/ExperimentDetail/EXPERIMENT_TAB_ASSET';
export const EXPERIMENT_TAB_MATPLOT = 'app/ExperimentDetail/EXPERIMENT_TAB_MATPLOT';
