export const LOAD_EXPERIMENT_DETAIL = 'app/ExperimentDetail/LOAD_EXPERIMENT_DETAIL';
export const LOAD_EXPERIMENT_DETAIL_SUCCESS = 'app/ExperimentDetail/LOAD_EXPERIMENT_SUCCESS';
export const LOAD_EXPERIMENT_DETAIL_ERROR = 'app/ExperimentDetail/LOAD_EXPERIMENT_ERROR';

export const CREATE_EXPERIMENT_LABELS = 'app/ExperimentDetail/CREATE_EXPERIMENT_LABELS';
export const CREATE_EXPERIMENT_LABELS_SUCCESS = 'app/ExperimentDetail/CREATE_EXPERIMENT_LABELS_SUCCESS';
export const CREATE_EXPERIMENT_LABELS_ERROR = 'app/ExperimentDetail/CREATE_EXPERIMENT_LABELS_ERROR';

export const DELETE_EXPERIMENT_LABELS = 'app/ExperimentDetail/DELETE_EXPERIMENT_LABELS';
export const DELETE_EXPERIMENT_LABELS_SUCCESS = 'app/ExperimentDetail/DELETE_EXPERIMENT_LABELS_SUCCESS';
export const DELETE_EXPERIMENT_LABELS_ERROR = 'app/ExperimentDetail/DELETE_EXPERIMENT_LABELS_ERROR';
