# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-15 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0003_invitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('project', 'user')]),
        ),
    ]
