# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0004_auto_20180315_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='detail_hash',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/assets/img/profile_pic.png', upload_to=''),
        ),
    ]
