# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0006_auto_20180320_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='detail_hash',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
