# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-20 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0007_auto_20180320_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinelearningmodel',
            name='detail_hash',
        ),
    ]
