# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0009_auto_20180322_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='platform',
            field=models.CharField(blank=True, choices=[('PYTHON', 'Python'), ('R', 'R'), ('JULIA', 'Julia'), ('EXCEL', 'Excel')], default='', max_length=200),
        ),
    ]
