# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-02 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0011_specialinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='platform_library',
            field=models.CharField(blank=True, choices=[('1', 'Sklearn'), ('2', 'Keras')], default='', max_length=5),
        ),
    ]
