# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0013_machinelearningmodel_deep_learning_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='ml_model_file',
            field=models.FileField(null=True, upload_to='model/'),
        ),
    ]
