# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-10 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0014_machinelearningmodel_ml_model_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='code_file',
            field=models.FileField(null=True, upload_to='code/'),
        ),
    ]
