# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-15 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0015_machinelearningmodel_code_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='key',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
