# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-05 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0016_membership_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_id',
        ),
    ]
