# Generated by Django 2.0.6 on 2018-06-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0020_experiment_remove_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='algorithm',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='platform',
            field=models.CharField(blank=True, choices=[('PYTHON', 'Python'), ('R', 'R'), ('JULIA', 'Julia'), ('EXCEL', 'Excel')], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='platform_library',
            field=models.CharField(blank=True, choices=[('1', 'Sklearn'), ('2', 'Keras')], default='', max_length=5, null=True),
        ),
    ]
