# Generated by Django 2.0.6 on 2018-06-25 17:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0021_auto_20180625_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='deep_learning_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='evaluation_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='features',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='model_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
