# Generated by Django 2.0.6 on 2018-07-02 14:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0022_auto_20180625_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='epoch_durations',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
