# Generated by Django 2.0.6 on 2018-07-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0023_machinelearningmodel_epoch_durations'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='experiment_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='machinelearningmodel',
            name='experiment_start',
            field=models.DateTimeField(null=True),
        ),
    ]
