# Generated by Django 2.0.6 on 2018-07-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0026_auto_20180702_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
