# Generated by Django 2.0.6 on 2018-07-28 14:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0031_machinelearningmodel_dataset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='code_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='code/'),
        ),
    ]
