# Generated by Django 2.0.6 on 2018-07-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0032_auto_20180728_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentCustomObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('filesize', models.BigIntegerField(default=None, null=True)),
                ('custom_object_file', models.FileField(null=True, upload_to='custom_object/')),
                ('custom_object_id', models.CharField(default=None, max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_object_experiment', to='modelchimp.MachineLearningModel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_object_project', to='modelchimp.Project')),
            ],
        ),
    ]
