# Generated by Django 2.0.6 on 2018-08-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0035_auto_20180815_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
