# Generated by Django 2.0.6 on 2018-08-27 08:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0036_auto_20180821_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_dict', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('epoch', models.IntegerField(default=None, null=True)),
                ('experiment_image', models.FileField(null=True, upload_to='experiment_image/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_experiment', to='modelchimp.MachineLearningModel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_project', to='modelchimp.Project')),
            ],
        ),
    ]
