# Generated by Django 2.0.6 on 2018-08-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0037_experimentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentimage',
            name='custom_file_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
