# Generated by Django 2.0.6 on 2018-09-03 11:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0038_experimentimage_custom_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='labels',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
