# Generated by Django 2.0.6 on 2018-09-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0038_experimentimage_custom_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentMatPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('filesize', models.BigIntegerField(default=None, null=True)),
                ('mat_plot_file', models.FileField(null=True, upload_to='mat_plot/')),
                ('mat_plot_id', models.CharField(default=None, max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mat_plot_experiment', to='modelchimp.MachineLearningModel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mat_plot_project', to='modelchimp.Project')),
            ],
        ),
    ]
