# Generated by Django 2.0.6 on 2018-09-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0039_experimentmatplot'),
        ('modelchimp', '0039_machinelearningmodel_labels'),
    ]

    operations = [
    ]
