# Generated by Django 2.0.6 on 2018-10-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0040_merge_20180914_0952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialInvite',
        ),
    ]
