# Generated by Django 2.1.3 on 2018-11-15 08:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0041_delete_specialinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinelearningmodel',
            name='model_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
