# Generated by Django 2.1.3 on 2019-01-09 16:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0042_auto_20181115_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinelearningmodel',
            name='grid_search',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
