# Generated by Django 2.1.3 on 2019-02-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0044_auto_20190130_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinelearningmodel',
            name='deep_learning_parameters',
        ),
    ]
