# Generated by Django 2.1.7 on 2019-02-21 15:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0045_remove_machinelearningmodel_deep_learning_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_dict', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('asset', models.FileField(null=True, upload_to='asset/')),
                ('custom_file_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('ml_model', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_experiment', to='modelchimp.MachineLearningModel')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_project', to='modelchimp.Project')),
            ],
        ),
    ]
