# Generated by Django 2.2 on 2019-05-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0047_auto_20190221_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachineLearningModel',
            new_name='Experiment',
        ),
    ]
