# Generated by Django 2.2 on 2019-05-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0048_auto_20190515_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='features',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='platform_library',
        ),
    ]
