# Generated by Django 2.2 on 2019-05-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelchimp', '0050_auto_20190516_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'In Process'), (2, 'Completed')], default=2, null=True),
        ),
    ]
